# Generated by Django 5.1.5 on 2025-05-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_customuser_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Doit changer le mot de passe'),
        ),
    ]
