# Generated by Django 5.1.5 on 2025-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('En fonctionnement', 'En fonctionnement'), ('En Panne', 'En Panne'), ('En Maintenance', 'En Maintenance')], max_length=50),
        ),
    ]
