# Generated by Django 5.1.5 on 2025-05-06 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='lieu_correction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='photo_piece',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_photos/'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='rapport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='tech_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('En fonctionnement', 'En fonctionnement'), ('En Panne', 'En Panne'), ('En Maintenance', 'En Maintenance')], default='En fonctionnement', max_length=20),
        ),
    ]
