# Generated by Django 5.1.5 on 2025-05-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='niveau_urgence',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('élevé', 'Élevé')], default='moyen', max_length=10),
        ),
    ]
