# Generated by Django 5.1.5 on 2025-05-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_panne_niveau_urgence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
