# Generated by Django 5.1.5 on 2025-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_rename_user_notification_recipient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
