# Generated by Django 5.1.5 on 2025-06-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='tech_group',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Information'), ('alerte', 'Alerte'), ('panne', 'Panne')], max_length=10),
        ),
    ]
