# Generated by Django 5.1.5 on 2025-06-22 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_remove_maintenance_date_remove_maintenance_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur'), ('technicien', 'Technicien')], max_length=20),
        ),
        migrations.AlterField(
            model_name='panne',
            name='signalee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
