"""
Django settings for equipment_management project.

Generated by 'django-admin startproject' using Django 5.1.5.
"""

import os
from pathlib import Path

# ================================
# 🔧 Chemins de base
# ================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================
# 🔐 Clé secrète & débogage
# ================================
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-xtpu-yw(rmzgp)iash9y)!d)!eql8@&+@f3rhri=o75!_bt5)n")
DEBUG = True
ALLOWED_HOSTS = [
    'equipment-management-tpse.onrender.com',
    'equipment-management-2.onrender.com',
    'localhost',
    '127.0.0.1'
]


# ================================
# 👤 Authentification
# ================================
AUTH_USER_MODEL = 'equipment.CustomUser'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'equipment.backends.EmailBackend',
]
LANGUAGE_CODE = 'fr'

USE_I18N = True
USE_L10N = True

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ================================
# 📦 Applications installées
# ================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Applications locales
    'equipment',
    # Extensions & outils externes
    'widget_tweaks',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'django_filters',
    'django_extensions',    
    'dal',
    'dal_select2',

]

# ================================
# ⚙️ Middleware
# ================================
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

# ================================
# 🧩 Configuration des templates
# ================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# ================================
# 🔑 تحميل متغيرات البيئة
# ================================
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# ================================
# 🗄 قاعدة البيانات
# ================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'equipment_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'aya2004'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# ================================
# 🛠 إعدادات التطبيق الرئيسي
# ================================
ROOT_URLCONF = 'equipment_management.urls'
WSGI_APPLICATION = 'equipment_management.wsgi.application'

# ================================
# 🔐 Validation des mots de passe
# ================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ================================
# 🌍 Internationalisation
# ================================



LANGUAGE_CODE = 'fr'
USE_I18N = True
USE_L10N = True

# ================================
# 📁 Fichiers statiques & médias
# ================================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# ================================
# 🔄 REST Framework
# ================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# ================================
# 🌐 CORS & CSRF
# ================================
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_HTTPONLY = False

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

# ================================
# 🆔 Type de clé primaire par défaut
# ================================

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # تخزين الجلسات في قاعدة البيانات
SESSION_COOKIE_NAME = 'sessionid'  # اسم الكوكيز الذي يحتوي على معرف الجلسة

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # 1 ساعة
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # الجلسة تنتهي عند إغلاق المتصفح
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ayaghimouze594@gmail.com'  # استبدل ببريدك الحقيقي
EMAIL_HOST_PASSWORD = 'hionsshrtmfpdvnz'   # الصق كلمة مرور التطبيق هنا بدون فراغات
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# مكان تجميع الملفات الثابتة
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # أو أي مسار تريد
